version: "3"
services:
  dotnetcontainer:
    build: .
    image: dotnet
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ENV: "DEV"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: "crypticpassword"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:  
      -  C:\\Users\\admin\\.aspnet\\https:/https/
      -  F:\\Code\\my\\dotnet-docker\\src\\aspnetcore:/app

